### ISSUE TITLE
help please, how do I download the file?

### ISSUE THREAD

**Issue by new-guy-cloud** [eustas/pelecyodon#1]
I'm trying to use your program to play Darkest Dungeon on my MacBook Air without melting the machine at the temperature of mt. vesuvius, could you help me with the instructions, please?

It says: download pelecyodon, but all I see is computer code and I don't know what to do with it, I'm not literate in this and I don't want to break my machine. does it go in the Terminal. Thank you :)

**Comment by eustas** [comment]
Well, the whole program is a tiny "Python" script. This way it is easier to see that program doesn't do anything bad and not a kind of malware =)
"Python" scripts could be simply run, because OSX has preinstalled Python interpreter.

README contains step-by-step instructions, but I agree, perhaps I have to make it more user-friendly.
Going to investigate, if it is possible to wrap script it "just click to run" something for improving UX, as well as adding some UI (to type-in target game name and throttling parameters).

Thanks for your interest.

**Comment by eustas** [comment]
About downloading: when you click on link in README, it shows the code, indeed. To actually "download" it, just click Cmd-S and choose the place where to save the file.

**Comment by new-guy-cloud** [comment]
I'm trying to get it right, don't know if it's worth looking into further anyway but here is what I've done so far. 
Here's the view after I saved the python file and entered the text in Terminal. Maybe this isn't in correct. 
![Screen Shot 2020-06-25 at 2 35 23 AM](https://user-images.githubusercontent.com/67410764/85697710-e1e95d00-b68e-11ea-94d8-fd9886772915.png)

Something is wrong, the computer fan came on immediately and it started getting hot,  and here's the Activity Monitor
![Screen Shot 2020-06-25 at 2 37 40 AM](https://user-images.githubusercontent.com/67410764/85697982-1ceb9080-b68f-11ea-9011-0481a64e4c97.png)

I have a MacBook Air, 2013, OS Mojave 10.14. Assuming I have the program running properly maybe it's the computer.

**Comment by eustas** [comment]
You should:
 * either quote the game name, like `"Darkest Dungeon"` (because whitespace is a parameter separator)
 * or shorten the game name to be just `Darkest`; pelecyodon checks if the target name is the part of executed program name

**Comment by new-guy-cloud** [comment]
I got ValueError... so I changed it to 15 instead of .15, and it seems to be working :) The fan hasn't even turned on. I haven't seen the CPU above 50, and it goes down to around 15 in a lot of moments. 

The sound and music did get dropped though, but that's not the biggest issue to me.

**Comment by new-guy-cloud** [comment]
the sound is working, that may have been unrelated not sure what I did.

**Comment by eustas** [comment]
You are right -- `0.15` / `0.20` were used in previous version; now it is "percentage" =) will fix README soon.
